import Head from "next/head";
import Link from "next/link";
import { ReactNode } from "react";
import { useRouter } from "next/router";

const Layout: React.FC<{ meta: any; sitemap: any; children: ReactNode }> = ({
  meta,
  sitemap,
  children,
}) => {
  const router = useRouter();
  const { locales } = router;

  return (
    <div style={{ padding: "50px", display: "flex", justifyContent: "center" }}>
      <Head>
        <title>{meta.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: "flex", flexDirection: "row" }}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            backgroundColor: "lightblue",
            padding: "10px",
          }}
        >
          {locales?.map((locale) => (
            <div
              key={locale}
              style={{
                display: "flex",
                flexDirection: "column",
                marginBottom: "5px",
              }}
            >
              <strong>{locale}</strong>
              {sitemap[locale].map((url: any) => {
                return (
                  <Link href={url} locale={locale as string} key={url}>
                    {url}
                  </Link>
                );
              })}
            </div>
          ))}
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            backgroundColor: "lightgreen",
            padding: "10px",
          }}
        >
          {children}
        </div>
      </div>
    </div>
  );
};

export default Layout;
